# Generated by Django 5.2.5 on 2025-08-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='studybox.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
