# Generated by Django 5.2.5 on 2025-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybox', '0002_documents_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='pdf_file',
            field=models.URLField(max_length=500),
        ),
    ]
