# Generated by Django 5.2.5 on 2025-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbox', '0003_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
